app/views/devise/registrations/new.html.erb
Have updated the sign-up form.
=> updated sign up form

app/assets/stylesheets/components/_boat_card.scss, app/assets/stylesheets/components/_home_index.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb
=> added index design grid

app/assets/stylesheets/components/_home_index.scss, app/views/pages/home.html.erb
added a footer to the index page
=> added footer to index page

app/assets/stylesheets/components/_home_index.scss, app/views/pages/home.html.erb
added a button to take us from the index page to the "create new boat page"
=> added a link to the list your boat page

app/assets/stylesheets/pages/_index.scss, app/views/boats/new.html.erb, config/environments/production.rb
I added a change to the congfig/env/production file to help with upload to heroku
=> fixed broken heroku reference in config env file

app/assets/stylesheets/pages/_boat-show.scss, app/assets/stylesheets/pages/_index.scss, app/views/boats/show.html.erb, app/views/layouts/application.html.erb
Added additional CSS and HTML to show page
=> added scss and html

app/assets/stylesheets/components/_home_index.scss, app/controllers/pages_controller.rb, app/views/boats/new.html.erb, app/views/pages/home.html.erb
we have removed all placeholder content and replaced it with the actual database content
=> now using database content for thecards

app/assets/stylesheets/pages/_boat-show.scss, app/views/boats/show.html.erb
Added picture frames with copyright free images
=> added picture frames with copyright free images

app/assets/stylesheets/pages/_index.scss, app/views/boats/show.html.erb, app/views/bookings/create.html.erb, app/views/shared/_navbar.html.erb
=> added logo

app/assets/stylesheets/components/_boat_card.scss, app/assets/stylesheets/components/_home_index.scss, app/views/boats/show.html.erb
Hi all, I changed the landing page to accommodate 4 columns and to add a small grow transition when you hover over a tile.
=> added grow transition to tiles and moved to 4-column grid

app/assets/stylesheets/pages/_boat-show.scss, app/controllers/boats_controller.rb, app/controllers/bookings_controller.rb, app/views/boats/show.html.erb
=> added booking functionality to show page

app/assets/stylesheets/pages/_boat-show.scss, app/views/boats/new.html.erb, app/views/boats/show.html.erb
=> added list with details and corrected picture frame

app/assets/stylesheets/components/_boat_card.scss, app/assets/stylesheets/components/_home_index.scss
=> grid now working

app/assets/stylesheets/pages/_login.scss, app/views/devise/sessions/new.html.erb
the login page layout has been updated.
=> updated login page

app/assets/stylesheets/pages/_index.scss, app/controllers/bookings_controller.rb, app/views/boats/show.html.erb, app/views/bookings/show.html.erb, app/views/pages/home.html.erb, config/routes.rb
=> final edits

app/assets/stylesheets/components/_boat_card.scss, app/assets/stylesheets/components/_home_index.scss, app/assets/stylesheets/pages/_booking_show.scss, app/views/bookings/show.html.erb
=> improved tile layout

.gitignore, app/controllers/boats_controller.rb, app/models/boat.rb, app/models/user.rb, app/views/boats/new.html.erb, app/views/boats/show.html.erb, app/views/pages/home.html.erb
Now we can include multiple pictures
=> Multiple pictures

app/views/bookings/show.html.erb, app/views/shared/_navbar.html.erb
changed a link on the booking confirmation page
=> changed link to dashboard

app/assets/stylesheets/pages/_booking_show.scss, app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, app/views/bookings/show.html.erb, app/views/users/show.html.erb
added a scsss file to style the dashboard
=> layout now with css

app/assets/stylesheets/components/_banner.scss, app/views/boats/show.html.erb, app/views/pages/home.html.erb
updates images and started banner
=> updates images and started banner

app/assets/stylesheets/pages/_boat-show.scss, app/controllers/boats_controller.rb, app/views/boats/show.html.erb
Changed show page to accommodate map and user image uploads
=> changed design of show page to accomodate map and user images

app/assets/stylesheets/components/_home_index.scss, app/assets/stylesheets/pages/_booking_show.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/bookings/show.html.erb, app/views/users/show.html.erb
moved the footer on the dashboard and booking confirmation pages to the bottom of the page (ish)
=> moved footer to end of page
